const fs = require('fs-extra');
const { execSync } = require('child_process');
const path = require('path');


// ---- Extract test results from Playwright JSON ----
function extractPlaywrightResults() {
  const resultsPath = path.join(__dirname, '../test-results/results.json');
  if (!fs.existsSync(resultsPath)) {
    console.warn('⚠️ No test results found at', resultsPath);
    return { summary: 'No results found', table: '| Test | Status | Duration (ms) |' };
  }

  const data = JSON.parse(fs.readFileSync(resultsPath, 'utf8'));
  const tests = [];

  function walkSuites(suites = []) {
    for (const suite of suites) {
      if (suite.tests) {
        suite.tests.forEach(test => {
          tests.push({
            name: test.title,
            status: test.outcome || test.status || 'unknown',
            duration: test.duration || 0
          });
        });
      }
      if (suite.suites) walkSuites(suite.suites);
    }
  }

  walkSuites(data.suites || []);

  const total = tests.length;
  const passed = tests.filter(t => t.status === 'passed').length;
  const failed = tests.filter(t => t.status === 'failed').length;
  const skipped = tests.filter(t => t.status === 'skipped').length;

  const summary = `**Total:** ${total} ✅ **Passed:** ${passed} ❌ **Failed:** ${failed} ⚪ **Skipped:** ${skipped}`;
  const table =
    '| Test | Status | Duration (ms) |\n|------|---------|---------------|\n' +
    tests
      .map(
        t =>
          `| ${t.name} | ${
            t.status === 'passed'
              ? '✅ Passed'
              : t.status === 'failed'
              ? '❌ Failed'
              : '⚪ Skipped'
          } | ${t.duration} |`
      )
      .join('\n');

  return { summary, table };
}

const REPORT_FOLDER = 'GQ_Assessment_Report';
const MD5_FILE = `${REPORT_FOLDER}/md5_report.txt`;
const README_FILE = 'README.md';

// Ensure report folder exists
fs.ensureDirSync(REPORT_FOLDER);

// Step 1: Generate MD5 checksums
console.log('Generating MD5 checksums...');
execSync(`> ${MD5_FILE}`);
execSync(`find . -type f ! -path "*/.*" | while read file; do md5 -r "$file" >> ${MD5_FILE}; done`);
console.log('MD5 report saved at', MD5_FILE);

// Step 2: Prepare MD5 summary table (top 10 files)
const md5Lines = fs.readFileSync(MD5_FILE, 'utf8').split('\n').filter(Boolean);
const md5Table = md5Lines.slice(0, 10).map(line => {
  const [hash, file] = line.split(' ');
  return `| ${hash} | ${file || ''} |`;
}).join('\n');

// Step 3: Prepare Playwright test summary dynamically
const PLAYWRIGHT_REPORT_JSON = path.join(REPORT_FOLDER, 'playwright-report', 'report.json');

let testSummary = '| Test Case | Status |\n|-----------|--------|\n';
if (fs.existsSync(PLAYWRIGHT_REPORT_JSON)) {
  const reportData = fs.readJSONSync(PLAYWRIGHT_REPORT_JSON);

  reportData.suites.forEach(suite => {
    suite.specs.forEach(spec => {
      spec.tests.forEach(test => {
        const status = test.results.every(r => r.status === 'passed') ? '✅ Passed' : '❌ Failed';
        testSummary += `| ${test.title} | ${status} |\n`;
      });
    });
  });
} else {
  testSummary += '| No tests found | - |\n';
}
if (fs.existsSync(PLAYWRIGHT_REPORT_JSON)) {
  const reportData = fs.readJSONSync(PLAYWRIGHT_REPORT_JSON);
  reportData.suites.forEach(suite => {
    suite.specs.forEach(spec => {
      spec.tests.forEach(test => {
        const status = test.results.every(r => r.status === 'passed') ? 'Passed' : 'Failed';
        testSummary += `| ${spec.file} | ${status} |\n`;
      });
    });
  });
} else {
  testSummary += '| goQuant_cases.spec.js | See HTML report |\n';
}

// Define credentials before the template starts
const credentials = "Generated by Darshana Nehulkar | QA Automation";

// --------------- TRACE EVIDENCE SECTION ----------------
const evidenceSection = `
## 🎥 Test Execution Evidence

## 🎥 Test Execution Evidence for Structured cases trace
| #  | Test Case | Trace File | GitHub Link |
|--- |------------|-------------|-------------|
| 01 | Login with Invalid Credentials     | TC01_LoginInvalid_Creds.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC01_LoginInvalid_Creds.zip) |
| 02 | Login with Valid Credentials       | TC02_LoginValid_Creds.zip   | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC02_LoginValid_Creds.zip) |
| 03 | Add OKX Account                    | TC03_Add_Account_OKX.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC03_Add_Account_OKX.zip) |
| 04 | Add Binance USDM Account           | TC04_Add_Account_Binance_COINM.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC04_Add_Account_Binance_COINM.zip) |
| 04 | Add Binance COINM Account          | TC04_Add_Account_Binance_USDM.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC04_Add_Account_Binance_USDM.zip) |
| 05 | Modify Account with invalid details| TC05_Modify_Account_ivalid_details.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC05_Modify_Account_ivalid_details.zip) |
| 06 | Place Order Binance COINM          | TC06_Place_Binance_COINM_Order.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC06_Place_Binance_COINM_Order.zip) |
| 06 | Place Order Binance USDM           | TC06_Place_Binance_USDM_Order.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC06_Place_Binance_USDM_Order.zip) |
| 06 | Place Order OKX                    | TC06_Place_OKX_Market_Order.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC06_Place_OKX_Market_Order.zip) |
| 08 | Order Emptyr values Validation     | TC08_order_place_validation_errors.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC08_order_place_validation_errors.zip) |
| 09 | Validate Metrics.                  | TC09_validate_metrics.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC09_validate_metrics.zip) |
| 11 | Cancel All Working Orders          | TC11_cancelall_workingorders.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC11_cancelall_workingorders.zip) |
| 12 | Kill Edge                          | TC12_kill-edge.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC12_kill-edge.zip) |
| 13 | Liquidate Positions                | TC13_Liquidate_Positions.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC13_Liquidate_Positions.zip) |
| 14 | Switch to smart ordering           | TC14_Smart_order_routing.zip | [View Trace]https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC14_Smart_order_routing.zip) |
| 17 | Add account using invalid details  | TC17_Add_Invalid_Account.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC17_Add_Invalid_Account.zip) |
| 20 | Logout user                        | TC20_Logout.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC20_Logout.zip) |
| 21 | Modify Account using valid details | TC21_Modify_Account_valid_details.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC21_Modify_Account_valid_details.zip) |
| 22 | Login fields validations           | TC22_Login_with_black_email_password.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/Restructured_cases/TC22_Login_with_black_email_password.zip) |

## 🎥 Test Execution Evidence for non structured cases (Old)
Each test case has its own individual **Playwright trace recording** uploaded to GitHub.  
These traces include full steps, network logs, screenshots, and console logs for debugging.
| # | Test Case | Trace File | GitHub Link |
|---|------------|-------------|-------------|
| 01 | Login with Invalid Credentials | TC01_LoginInvalid_Creds.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/TC01_LoginInvalid_Creds.zip) |
| 02 | Login with Valid Credentials | TC02_LoginValid_Creds.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/TC02_LoginValid_Creds.zip) |
| 03 | Add Account | TC03_Add_Account.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/TC03_Add_Account.zip) |
| 04 | Delete Account | TC04_Delete_Account.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/TC04_Delete_Account.zip) |
| 05 | Modify Account (Invalid Details) | TC05_Modify_Account_Invalid_Details.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/TC05_Modify_Account_Invalid_Details.zip) |
| 06 | Place OKX Market Order | TC06_Place_OKX_Market_Order.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/TC06_Place_OKX_Market_Order.zip) |
| 07 | Get Order Details | TC07_Get_Order_Details.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/TC07_Get_Order_Details.zip) |
| 08 | Validation Errors | TC08_Validation_Errors.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/TC08_Validation_Errors.zip) |
| 09 | Validate Metrics | TC09_Validate_Metrics.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/TC09_Validate_Metrics.zip) |
| 10 | Add & Clear Assets | TC10_AddClear_Assets.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/TC10_AddClear_Assets.zip) |
| 11 | Cancel All Working Orders | TC11_CancelAll_WorkingOrders.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/TC11_CancelAll_WorkingOrders.zip) |
| 12 | Kill Edge | TC12_Kill_Edge.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/TC12_Kill_Edge.zip) |
| 13 | Liquidate Positions | TC13_Liquidate_Positions.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/TC13_Liquidate_Positions.zip) |
| 14 | Smart Order Routing | TC14_Smart_Order_Routing.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/TC14_Smart_Order_Routing.zip) |
| 20 | Logout | TC20_Logout.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/TC20_Logout.zip) |
| 21 | Modify Account (Valid Details) | TC21_Modify_Account_Valid_Details.zip | [View Trace](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/tests/trace/TC21_Modify_Account_Valid_Details.zip) |

> 🧩 **Note:** All traces are downloadable ZIPs and can be replayed using Playwright Trace Viewer.
`;

// Step 4: Generate dynamic README content
const readmeContent = `
# GQ_Assessment Automation Framework

# 1. Project Description
This automation framework validates the GoQuant platform workflows including account add, account management, order placement, API validations, and UI testing, Cross Browser Testing.
------------------------------------------------------------------------------

# 2. 🧭 Executive Summary
This report outlines the automated testing process performed on GoQuant’s GoTrade platform.  
The tests covered functional, UI/UX, and edge case scenarios.  
Overall, the platform demonstrated basic stability, with several functional and validation issues identified.
------------------------------------------------------------------------------

## 3. Technologies and Frameworks Used
- **Programming Language:** JavaScript / Node.js  
- **Automation Framework:** Playwright  
- **Reporting Tools:** Playwright HTML Reporter, Markdown, PDF generation ('markdown-pdf')  
- **Approach:** End-to-end automation using Page Object Model 
- **Execution:** Manual + Automated API validations 
- **Browsers:** Chromium, Firefox, Safari 
- **Data Management:** Hardcoded credentials and test data files 
- **Build Tools:** npm  
- **Other Tools:** fs-extra (file system utilities), MD5 checksum verification  
------------------------------------------------------------------------------

## 4. Prerequisites
- Node.js v18+
- npm 
- Playwright browsers installed
- Git
- Modern browser (Chromium, Firefox, Safari)
------------------------------------------------------------------------------

## 5. Installation
\`\`\`
git clone -b GQ_Assessment https://github.com/Darshana-BS/GQ_Assessment.git
cd GQ_Assessment
npm install
npx playwright install
\`\`\`
------------------------------------------------------------------------------

## 6. How to Run Tests
\`\`\`
# Run all tests
npx playwright test --reporter=html
npx playwright show-report

# View Video recording trace 
npx playwright show-trace trace/<.zip file name>
ex. npx playwright show-trace trace/TC05_Modify\ Account.zip

# Run specific test
npx playwright test tests/goQuant_cases.spec.js

# Run tests in headless mode 
npx playwright test --headless 

# Run tests in head mode 
npx playwright test --headed  

# Run tests to save /test-results/resultsjson results 
npx playwright test --reporter=json,html --output=playwright-report > /Users/darsh_cf/Desktop/DN_cypress/GoQuant_Auto_Asse/test-results/results.json --project=chromium --headed
npm run test:report 

# Run test to copy report with date, time and to github automaticaly 
"test:reportcopy": "npx playwright test --reporter=html && node copyReport.js"

# Run cases and save browser specific results in <browser_name>_results 
"test:chrome": "npx playwright test --project=chromium --reporter=html --output=chrome_results",
"test:firefox": "npx playwright test --project=firefox --reporter=html --output=firefox_results",
"test:safari": "npx playwright test --project=webkit --reporter=html --output=webkit_results",

# Generate MD5 checksums
mkdir -p GQ_Assessment_Report
find . -type f ! -path "*/.*" -print0 | xargs -0 -I{} md5 -r {} > GQ_Assessment_Report/md5_report.txt 

# Generate combined PDF report 
node generateReport.js
\`\`\`
------------------------------------------------------------------------------

# 7. Project Structure
\`\`\`
pages/                    # Page object models for UI interactions
tests/                    # Playwright test scripts
fixtures/                 # Test data and reusable assets
GQ_Assessment_Report/     # Generated MD5, HTML, and PDF reports
package.json              # Node.js project configuration
generateReport.js         # Script to generate MD5 + Playwright PDF report
playwright.config.js      # Configs for tests being executed
\`\`\` 
------------------------------------------------------------------------------

## 8. Reporting and Results
\`\`\`
**Top 10 MD5 files:**
MD5 Report: GQ_Assessment_Report/md5_report.txt — lists MD5 hashes of all project files for integrity check
Playwright HTML Report: GQ_Assessment_Report/playwright-report/index.html — detailed pass/fail report for all test cases
Combined PDF Report: GQ_Assessment_Report/Detailed_Report.pdf — single file containing project overview, MD5 summary, and test results
| Hash | File |
${md5Table}
${credentials}
\`\`\`
------------------------------------------------------------------------------

## 9. 🧪 Test Case Overview
| Category   | Scenarios  | Tools Used |
|----------- |------------|------------|
| Functional | Login validation, Account creation, Account Modify, Account Delete, Place Order, Validate Account status, Get order details, Cancel Order API, Switch Views, Log out | Playwright |
| UI/UX      | Page elements, modal handling, dropdowns | Playwright |
| Edge Case  | \`/gotrade/v3/users\` | Playwright |
| API        | \`/gotrade/v3/credentials\`, \`/gotrade/v3/cancel_all\` | Playwright APIRequest |

*Total Tests: **22**  
*Passed: **14**  
*Failed (Expected): **2**
------------------------------------------------------------------------------

## 10 🧩 Challenges Faced
- Dynamic IDs ('radix-*') made locators unstable.
- Modal elements required explicit waits.
- GitHub push blocked due to PAT (resolved by removing file and rewriting history).
- Playwright Test did not expect test() to be called here (due to hat means you have nested playwright dependencies — 
  usually happens if some other dependency also includes @playwright/test.)
------------------------------------------------------------------------------

## 11. Known Bugs / Notes
- Update API sometimes returns 400 (handled)
- Cancel Order API sometimes returns 422 (handled) 
- Orders are placed but not displayed in the orders history (coult not automate, as there are no orders) 
- Cancel single orders are not displayed due to order issue (could not automate, as there are no orders)

### 🪲 Key Findings

### 🔴 Critical
| ID | Issue  | Expected vs Actual | Steps to Reproduce |
|----|--------|--------------------|--------------------|
| 1  | Orders are not displayed in the order history | Should display the orders placed successfully | Execute the place order api and validate orders |
| 2  | API \`/gotrade/v3/cancel_all\`' response delayed | Should return < 200ms | Execute cancel API in test |

### 🟡 Medium
| ID | Issue  | Observation | Evidence  |
|----|--------|-------------|-----------|
| 3  | Modify Account is displaying incorrect message  | Modify account from Accounts and save | [Pending] Attached screenshot |
| 4  | Metrics data total and assets column data is inconsistent | Metrics validate TC09_validation_Metrics_ | Check results summary |

### 🟢 Low
| ID | Issue  | Observation | Note |
|----|--------|-------------|------|
| 5  | Sometimes env abruptly lands on 'Something went wrong' | Execute case TC22[Edge_case]_Handle_Something_went_wrong | Environment Issue |
| 6  | Try again on 'Something went wrong' screen is not functioning | Execute case TC22[Edge_case]_Handle_Something_went_wrong | Environment Issue |
| 7  | APIs \`/v4/groups/all\`, \`/v3/set_margin_leverage\`, \`/v3/symbols/leverage-margin\`, \`/v3/current_leverage_margin\` | Failing with 400 Bad request | Navigate / Visit https://test1.gotrade.goquant.io/admin| 
| 8  | APIs \`/v1/users\` | Failing with 500 Error | Navigate / Visit https://test1.gotrade.goquant.io/admin | 

------------------------------------------------------------------------------

## 12. 📈 Technical Analysis
- **Average API response time:** 280ms  
- **Browser coverage:** 3  
- **Accessibility:** 
- **Performance:** Stable under 5 concurrent actions 
------------------------------------------------------------------------------

## 13. 💡 Recommendations
- Add stable 'data-testid' attributes for better element targeting.
- Optimize API response time under 200ms.
- Improve accessibility attributes (aria-labels, alt text).
- Enhance error message consistency. 
- Add a better UI handeling for the screen elements of the Add/Clear button (expected = dropdown to select % should stay until user clicks somwhere elese)
------------------------------------------------------------------------------

## 14. 📸 Evidence & Reports
| 🧾 Type | 📁 Location | 🔗 Open / Notes |
|----------|--------------|----------------|
| 🧠 **HTML Test Report** | [GQ_Assessment_Report/playwright-report/index.html](./GQ_Assessment_Report/playwright-report/index.html) | ▶️ *View full Playwright test results* |
| 🧠 **PDF Test Report | [GQ_Assessment_Report/GQ_Assessment_Report/Detailed_Report.md](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/GQ_Assessment_Report/GQ_Assessment_Report/Detailed_Report.md) | 🪄 *Backup local report location* |
| 🧩 **Trace Files** | [tests/trace/Restructured_cases](https://github.com/Darshana-BS/GQ_Assessment/tree/GQ_Assessment/tests/trace/Restructured_cases) | 🔍 *Replay test steps in Playwright trace viewer* |
| 🖼️ **Screenshots** | [reports/screenshots/](./reports/screenshots/) | 📸 *Pending upload / captured test images* | [Pending]
------------------------------------------------------------------------------ 

## 15. 🧩 Test Organization
All Playwright test cases are placed under the \`tests/\` directory.  
Each module or functionality has its own \`.spec.js\` file for better organization.

\`\`\`bash
tests/
├── account/
│   ├── TC03_Add_Account_OKX.spec.js
│   ├── TC04_Add_Account_Binance_COINM.spec.js
│   ├── TC04_Add_Account_Binance_USDM.spec.js
│   ├── TC05_Modify_Account_Invalid_details.spec.js
│   ├── TC17_Add_Invalid_account.spec.js
│   ├── TC18_Delete_Account.spec.js
│   ├── TC19_Validate_Account_Status.spec.js
│   ├── TC20_Modify_Account_Valid.spec.js
│   └── TC21_Add_Account_Valid.spec.js

├── auth/
│   ├── TC01_LoginInvalid_Creds.spec.js
│   ├── TC02_LoginValid_Creds.spec.js
│   ├── TC20_Logout.spec.js
│   └── TC22_Login_with_black_email_password.spec.js

├── dashboard/
│   ├── [Pending]_TC15_Switch_to_Order_book_Consolidated_view.spec.js
│   ├── TC09_Validate_Metrics.spec.js
│   ├── TC10_add_clear_assets.spec.js
│   ├── TC12_Kill_Edge.spec.js
│   ├── TC13_Liquidate_Positions.spec.js
│   └── TC14_Switch_to_smart_order_routing.spec.js

└── order/
    ├── TC06_Place_Binance_COINM_order.spec.js
    ├── TC06_Place_Binance_USDM_order.spec.js
    ├── TC06_Place_OKX_Market_order_swap.spec.js
    ├── TC08_Place_order_validations_with_empty_details.spec.js
    ├── TC11_Cancel_All_Working_Orders.spec.js
    └── TC16_Place_Short_Sell_order.spec.js
\`\`\`

All 22 Playwright test cases are structured across feature-based spec files:

| Module                | Test Cases                    | Folder              |
|-----------------------|-------------------------------|---------------------|
| Authentication        | TC01 – TC02, TC20 - T20       | \`/tests/auth/\`    |
| Account Management    | TC03 – TC05, TC17 - TC19, TC21| \`/tests/account/\` |
| Order                 | TC06, TC08, TC11, TC16        | \`/tests/order/\`  |
| Dashboard             | TC09 – TC10, TC12 - TC15      | \`/tests/api/\`     |

This structure improves test readability, modularity, and maintainability.

## 16. 🏷️ Tag-based Execution

| Command                                      | Description                         |
| ---------------------------------------------| ----------------------------------- |
| \`npx playwright test --grep "@auth"\`       | Run only authentication tests       |
| \`npx playwright test --grep "@account"\`    | Run only account-related tests      |
| \`npx playwright test --grep "@order"\`      | Run only order tests                |
| \`npx playwright test --grep "@dashboard"\`  | Run the full regression suite       |
| \`npx playwright test --grep-invert "@order"\`| Run all UI tests excluding API ones |

All Playwright tests are categorized with tags for selective execution:

| Tag       | Description                              |
|-----------|------------------------------------------|
| @auth     | Login & authentication flows             |
| @account  | Account creation, modification, deletion |
| @order    | Order placement & validation             |
| @dashboard| API endpoint validation                  |
| @logout   | Logout functionality                     |

**Run Examples:**
\`\`\`bash
npx playwright test --grep "@auth"
npx playwright test --grep "@order"
npx playwright test --grep-invert "@account"
------------------------------------------------------------------------------

## 17. ✨ Conclusion
The GoTrade application is functional but exhibits minor inconsistencies across UI and API layers.  
The automation suite is scalable, modular, and demonstrates readiness for integration into CI/CD.
------------------------------------------------------------------------------

\`\`\`
## 18. Author 
\`\`\`
👩‍💻 *Darshana Nehulkar*  
- GitHub: [https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/](https://github.com/Darshana-BS/GQ_Assessment/blob/GQ_Assessment/)
📅 *Date:* 29th October 2025  
📧 *dnehulkar805@gmail.com*
\`\`\`
`;

// Step #: Write README.md
fs.writeFileSync(README_FILE, readmeContent);
console.log('✅ Dynamic README.md updated!');

// Step #: Write MD5 
// fs.writeFileSync('GQ_Assessment_Report/md5_report.txt', report);
// console.log('MD5 report saved at GQ_Assessment_Report/md5_report.txt');

const summarySection = `
## 📋 Test Summary

This report summarizes the automated test results for the GoQuant Assessment project.
All test scripts were executed using **Playwright**, with supporting API tests via **Postman**.
Each module includes validation for login, account management, order execution, and API response integrity.
`;

const finalReport = `
# 🧠 GoQuant QA Assessment Report

${summarySection}

${evidenceSection}

${md5Table}

${credentials}
`;

//Generate detail report md5 and PDF 
fs.writeFileSync('./GQ_Assessment_Report/Detailed_Report.md', finalReport);

const markdownpdf = require('markdown-pdf');
fs.writeFileSync('./GQ_Assessment_Report/Detailed_Report.md', finalReport);
const outputDir = './GQ_Assessment_Report';

// Save Markdown version
const markdownPath = path.join(outputDir, 'Detailed_Report.md');
fs.writeFileSync(markdownPath, finalReport);
console.log('✅ Markdown report created successfully.');

// Convert Markdown to PDF
const pdfPath = path.join(outputDir, 'Detailed_Report.pdf');
markdownpdf()
  .from(markdownPath)
  .to(pdfPath, function () {
    console.log(`✅ PDF successfully generated: ${pdfPath}`);
  });


//Generate Live test status report 
function generateMarkdownReport() {
  const date = new Date().toLocaleString('en-IN');
  const resultFile = path.join(reportFolder, './GQ_Assessment_Report/json/test-results.json');
  let total = 0, passed = 0, failed = 0, skipped = 0;
  let browserStats = {}; // will hold browser-wise summary
  let testTable = '';

  if (fs.existsSync(resultFile)) {
    const data = JSON.parse(fs.readFileSync(resultFile, 'utf-8'));
    const tests = [];

    const extractTests = suite => {
      if (suite.tests) tests.push(...suite.tests);
      if (suite.suites) suite.suites.forEach(extractTests);
    };
    data.suites.forEach(extractTests);

    total = tests.length;
    passed = tests.filter(t => t.results?.some(r => r.status === 'passed')).length;
    failed = tests.filter(t => t.results?.some(r => r.status === 'failed')).length;
    skipped = tests.filter(t => t.results?.some(r => r.status === 'skipped')).length;

    // 🔹 Compute browser-wise summary
    for (const test of tests) {
      for (const result of test.results || []) {
        const browser = result.projectName || 'unknown';
        if (!browserStats[browser]) browserStats[browser] = { total: 0, passed: 0, failed: 0, skipped: 0 };
        browserStats[browser].total++;
        if (result.status === 'passed') browserStats[browser].passed++;
        else if (result.status === 'failed') browserStats[browser].failed++;
        else browserStats[browser].skipped++;
      }
    }

    // 🔹 Build test status table
    testTable = tests.map(t => {
      const name = t.title || 'Untitled';
      const status = t.results?.[0]?.status || 'unknown';
      const browser = t.results?.[0]?.projectName || '—';
      const duration = t.results?.[0]?.duration ? `${t.results[0].duration}ms` : '—';
      const icon = status === 'passed' ? '✅' : status === 'failed' ? '❌' : '⚪️';
      return `| ${name} | ${browser} | ${icon} ${status.toUpperCase()} | ${duration} |`;
    }).join('\n');
  } else {
    testTable = '| No test results found | — | — | — |';
  }

  // 🔹 Build browser summary table
  const browserTable = Object.keys(browserStats).length
    ? Object.entries(browserStats)
        .map(([browser, stats]) =>
          `| ${browser} | ${stats.total} | ${stats.passed} | ${stats.failed} | ${stats.skipped} |`)
        .join('\n')
    : '| — | — | — | — | — |';

  // 🔹 Trace table
  const traces = fs.existsSync(traceDir)
    ? fs.readdirSync(traceDir).filter(f => f.endsWith('.zip'))
    : [];
  const traceTable = traces.length
    ? traces.map(f => `| ${f} | [View Trace](../tests/trace/${f}) | ✅ |`).join('\n')
    : '| No traces found | — | — |';



  fs.writeFileSync(mdFile, md.trim());
  console.log(`✅ Markdown report saved with browser-wise stats: ${mdFile}`);
}

const crypto = require('crypto');

// Function to read Playwright JSON test results
function getPlaywrightResults() {
  const resultsPath = path.join(__dirname, '../test-results/results.json');
  if (!fs.existsSync(resultsPath)) {
    return { summary: 'No results found', tests: [] };
  }

  const data = JSON.parse(fs.readFileSync(resultsPath, 'utf8'));
  const tests = [];

  if (data.suites) {
    // recursively extract all tests
    function extractTests(suite) {
      if (suite.tests) {
        suite.tests.forEach(test => {
          tests.push({
            name: test.title,
            status: test.outcome || test.status || 'unknown',
            duration: test.duration || 0
          });
        });
      }
      if (suite.suites) suite.suites.forEach(extractTests);
    }
    data.suites.forEach(extractTests);
  }

  const passed = tests.filter(t => t.status === 'passed').length;
  const failed = tests.filter(t => t.status === 'failed').length;
  const total = tests.length;

  const summary = `Total Tests: ${total} | ✅ Passed: ${passed} | ❌ Failed: ${failed}`;
  return { summary, tests };
}

const { summary, table } = extractPlaywrightResults();
let resultsSection = `
## ✅ Summary of Last Execution
${summary}

## 📋 Detailed Test Results
${table}

`;

// --------------------------------------------------------------------
// 🧪 ADD PLAYWRIGHT RESULTS SUMMARY TO MARKDOWN
// --------------------------------------------------------------------
const resultsPath = './test-results/results.json';
resultsSection = '\n## 🧪 Latest Playwright Test Results\n';

try {
  if (fs.existsSync(resultsPath)) {
    const data = JSON.parse(fs.readFileSync(resultsPath, 'utf8'));
    const tests = [];

    // Flatten all test entries from nested suites
    if (data.suites) {
      for (const suite of data.suites) {
        if (suite.specs) {
          for (const spec of suite.specs) {
            const name = spec.title || spec.name || 'Unnamed Test';
            const status = spec.ok ? '✅ Passed' : '❌ Failed';
            tests.push(`- **${name}** — ${status}`);
          }
        }
      }
    }

    if (tests.length > 0) {
      resultsSection += tests.join('\n');
    } else {
      resultsSection += 'No tests found in the JSON file.\n';
    }
  } else {
    resultsSection += '⚠️ test-results/results.json not found.\n';
  }
} catch (err) {
  resultsSection += `⚠️ Error reading Playwright results: ${err.message}\n`;
}

// Append section safely to your report
if (typeof markdown === 'undefined') {
  markdown = '';
}
markdown += resultsSection;

// Save markdown to file to Generate Live test status md5 report
fs.writeFileSync('./GQ_Assessment_Report/Detailed_Tests_Status_Report.md', markdown);
console.log('✅ Detailed report updated with Playwright results.');

// Append to existing markdown variable 
markdown += `\n\n${resultsSection}`;
fs.writeFileSync('./GQ_Assessment_Report/Detailed_Tests_Status_Report.md', resultsSection); 

//PDF generate for live cases results status
// const { execSync } = require('child_process');
// try {
//   execSync(
//     'pandoc ./GQ_Assessment_Report/Detailed_Tests_Report.md -o ./GQ_Assessment_Report/Detailed_Tests_Report.pdf --pdf-engine=xelatex'
//   );
//   console.log('✅ PDF successfully generated with pandoc.');
// } catch (err) {
//   console.error('❌ PDF generation failed:', err.message);
// }
// fs.writeFileSync('./GQ_Assessment_Report/Detailed_Tests_Report.md', markdown);
// console.log('✅ Detailed report updated with Playwright results.');

// // 📄 Generate PDF from Markdown fpr Live status results 
// const pypandoc = require('pypandoc');
// const mdPath = './GQ_Assessment_Report/Detailed_Tests_Report.md';
// const statuspdfPath = './GQ_Assessment_Report/Detailed_Tests_Report.pdf';

// try {
//   pypandoc.convert_file(mdPath, 'pdf', {
//     outputfile: pdfPath,
//     extra_args: ['--standalone'],
//   });
//   console.log(`✅ PDF successfully generated: ${statuspdfPath}`);
// } catch (err) {
//   console.error(`❌ Failed to generate PDF: ${err.message}`);
// } 
// generateModuleReports.js
// const fs = require('fs');

const modules = ['auth', 'account', 'orders']; // add your folders here

modules.forEach(module => {
  console.log(`\n📦 Generating report for module: ${module}`);

  const moduleDir = `tests/${module}`;
  const reportDir = `GQ_Assessment_Report/${module}`;

  if (!fs.existsSync(moduleDir)) {
    console.log(`⚠️ Skipping ${module} — no tests found`);
    return;
  }

  try {
    // Run tests for this module
    execSync(`npx playwright test ${moduleDir} --reporter=html --output=${reportDir}`, { stdio: 'inherit' });
    console.log(`✅ Report generated at: ${reportDir}/index.html`);
  } catch (err) {
    console.error(`❌ Error running tests for ${module}:`, err.message);
  }
});
